WIP: Add Expanding and EWM.mean
python-streamz/streamz pull request #412
Opened 2021-03-22 04:47 UTC by mroeschke

xref #220

Proof of concept adding `expanding` and `ewm` ops. For `ewm`, I used pandas' ewm implementation.

2021-03-22 12:21 UTC, jreback requested changes
@mroeschke if u can add some tests esp to assert the NotImplemented

2021-03-29 19:47 UTC, jreback requested changes

2021-03-29 19:47 UTC, jreback commented on streamz/dataframe/core.py
> +            raise ValueError("Must pass one of com, span, halflife, or alpha")
are these all hit in tests?

2021-03-31 00:10 UTC, ramicaza commented
I started working on implementing EWMA today then halfway through I realized "hey I should probably check if there were any PRs in the last month since I last checked".  Then I found this haha. 

Anyways, I noticed there was no mention of "adjust" in your changes. My implementation currently computes a running adjusted EWM which is equivalent to the default pandas ewm: `pd.DataFrame.ewm(adjust=True)`.  I was wondering if your implementation is the adjusted or non-adjusted ewma.  I think it's pretty important to offer both of these in the streamz ewm.

2021-03-31 05:39 UTC, mroeschke commented on streamz/dataframe/core.py
> +            raise ValueError("Must pass one of com, span, halflife, or alpha")
Added tests for these.

2021-03-31 05:44 UTC, mroeschke commented
Agreed, and it would be great if you could follow up with those features @ramicaza! I don't think I'll be able to tackle that if/when this PR is merged in.

2021-04-02 05:45 UTC, mroeschke commented
@martindurant ready for a look when you get the chance (the failing test seems unrelated `test_kafka_batch_checkpointing_async_nodes_1`)

2021-04-05 16:02 UTC, martindurant commented
Agreed, same as in https://github.com/python-streamz/streamz/pull/411

2021-04-05 16:02 UTC, merged